### ISSUE TITLE
carthage update error: SetOwnerAndGroup, libgit2.a

### ISSUE THREAD

**Issue by phlebotinum** [SwiftGit2/SwiftGit2#114]
The current master branch ```[98fcae4]``` produces an error for me during ```carthage update --platform mac```.

```The following build commands failed: SetOwnerAndGroup <userName>:staff /Users/<userName>/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/SwiftGit2/98fcae405ee8af0642fa2984adb64f2e9c90a155/Build/Intermediates.noindex/ArchiveIntermediates/SwiftGit2-OSX/IntermediateBuildFilesPath/UninstalledProducts/macosx/libgit2.a```

To reproduce in a small test-app...
1. Created new Mac Cocoa App in Xcode 9.2
2. Created Cartfile with only ```github "SwiftGit2/SwiftGit2" "master"```in it.
3. Did ```carthage update --platform mac```

Afaik I have all required tools installed. They all show up with ```brew list```. Brew and Carthage are up-to-date. Updated all components with ```brew uprade```.

I don´t know much about the details of how carthage works and interacts with other systems nor about linux/filesystem aspects. So i don't have ideas about how to troubleshoot this further. Had a friend reproduce it on another system. If this is not really related to SwiftGit2 i would still be grateful for some actionable hints on how to troubleshoot this. Hoping for @mdiep and his carthage knowledge here, too.

**Comment by mdiep** [comment]
Hmm… this builds for me without any issues.

This seems very strange. Could you post the full build log? (Carthage will print the location of the log.)

**Comment by phlebotinum** [comment]
Sure. Thanks for looking into this. Let me know what else i can do .
https://gist.github.com/phlebotinum/42ca80e7558dd54ee8e5e6f4f1e6e4f6

**Comment by mdiep** [comment]
Well that's not very helpful. Can you try cloning the repo, running `script/bootstrap`, and then building in Xcode?

**Comment by phlebotinum** [comment]
That just built the macOS FW successfully.

**Comment by mdiep** [comment]
Maybe try deleting `~/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/SwiftGit2/` and building again?

**Comment by phlebotinum** [comment]
Sure.

Quick question, though. The whole folder ```org.carthage.CarthageKit``` has different - and to me weird looking - permissions ```user: Write only (Drop Box), staff: Custom, everyone: Write only (Drop Box)``` (WhyTF is Drop Box being mentioned there???) Oother folders in there have ```U: R&W, S:Ro, E:Ro``` which makes more sense to me. But i am not really a sysadmin/commandline guy. What do you think about that? Should i maybe delete the whole folder? Or would that harm anything? Meanwhile i will test to just delete the folder in there - like you wrote - and re-try.

**Comment by mdiep** [comment]
Okay, that's definitely the issue. You can probably either delete it or correct the permissions. `chown -R {{your username}}:staff ~/Library/Caches/org.carthage.CarthageKit`. (You may need to do that with `sudo`.)

**Comment by phlebotinum** [comment]
How TF did the DropBox get in there ? Am i hacked by the russians. Do they want to steal my vote ??? Ok seriously WTF is this?

**Comment by phlebotinum** [comment]
Ok. After deleting the whole Folder: ```~/Library/Caches/org.carthage.CarthageKit``` and doing ```carthage update --platform mac``` again the folder is back and this time all permissions look good, BUT the error is still there ?

**Comment by phlebotinum** [comment]
I just built it separately and added the frameworks manually and got rid of carthage.

**Comment by mdiep** [comment]
Okay, I was able to reproduce this. I initially had tried with a slightly outdated version of Carthage. Now that newer Carthage versions build with `xcodebuild archive`, SwiftGit2 is failing to build.
