### ISSUE TITLE
Operation not permitted when trying to use sample code and my url string is the path to my git repo.

### ISSUE THREAD

**Issue by jottenlips** [SwiftGit2/SwiftGit2#117]
Could not open repository: Optional(Error Domain=org.libgit2.libgit2 Code=-1 "Could not open '/Users/johnottenlips/somethingLikeAsteroids/.git/config': Operation not permitted" UserInfo={NSLocalizedDescription=Could not open '/Users/johnottenlips/somethingLikeAsteroids/.git/config': Operation not permitted, NSLocalizedFailureReason=git_repository_open failed.})

**Comment by mavris** [comment]
@jottenlips I am having the same issue. any tips?
