### ISSUE TITLE
"Unable to lock mwindow mutex" error trying to clone repo

### ISSUE THREAD

**Issue by stonehouse** [SwiftGit2/SwiftGit2#121]
I keep getting the following error when I try and clone a repo. Has anyone seen this before? I'm aware it's coming from libgit2, but I can't find any similar error reports. I've tried a few different credential types and different repos and I always get the same error. I seem to be able to get info about an existing repo or change branches without any issues.

_Error Domain=org.libgit2.libgit2 Code=-1 "unable to lock mwindow mutex" UserInfo={NSLocalizedDescription=unable to lock mwindow mutex, NSLocalizedFailureReason=git_clone failed.}_

```
let repoURL = URL(string: "https://github.com/antitypical/Result.git")!

let creds: Credentials = .sshAgent
let res = Repository.clone(from: repoURL, to: destinationURL, credentials: creds) { (state, p1, p2) in
	print("\(state) \(p1) \(p2)")
}

switch res {
case .success(let repo):
	print("\(repo)")
case .failure(let e):
	print("FAILURE \(e)")
}
```

**Comment by mdiep** [comment]
I haven't seen that error before.

I think our libgit2 version is quite out of date. If you're interested in opening a PR to update it, it's possible that it'll fix the issue.

**Comment by stonehouse** [comment]
Actually I think the issue might be that I'm using a newer version. I was working on getting Swift PM support working, and I got it working but using the system libgit2 installed via brew which is 0.26. I need to debug it a bit, I might see if updating the submodule causes the tests to fail. I'll open a new PR with Swift PM soon. I'll go ahead and close this.

**Comment by stonehouse** [comment]
Cause was that git init wasn't called in all cases in my branch.
