### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by lucascorrea** [SwiftGit2/SwiftGit2#131]
Hi everyone, I'm trying to use the framework but I received this error.
`No such file or directory`

Could you send me an example to clone, please?

I've tried it just a test of connection.

Thank you.

```
let url: URL = URL(string: "https://github.com/klaidliadon/tent-sample")!
        let repo = Repository.at(url)
        print(repo)
        if let repo = repo.value {
            let latestCommit: Result<Commit, NSError> = repo
                .HEAD()
                .flatMap { repo.commit($0.oid) }
            if let commit = latestCommit.value {
                print("Latest Commit: \(commit.message) by \(commit.author.name)")
            } else {
                print("Could not get commit: \(latestCommit.error)")
            }
        } else {
            print("Could not open repository: \(repo.error)")
        }
```

**Comment by mdiep** [comment]
You get that error from the code you shared? Which operation is failing?

**Comment by mdiep** [comment]
`Repository.at` opens a local repository. If you want to clone, you need to use `Repository.clone`.

**Comment by lucascorrea** [comment]
@mdiep Thanks. It worked.

I think that could put more examples on Readme.md

**Comment by mdiep** [comment]
> I think that could put more examples on Readme.md

Pull requests welcome! 😄
