### ISSUE TITLE
Xcode 10 swift 4.2 - Build Framework

### ISSUE THREAD

**Issue by lucascorrea** [SwiftGit2/SwiftGit2#134]
Hey everyone,

Someone did the build of the framework on Xcode 10 swift 4.2?

**Comment by arguiot** [comment]
When I'm trying to do it with Carthage, it fails

**Comment by fallback** [comment]
Just made a manual build of SwiftGit2-OSX under XCode 10.1, with Swift Language Version set to 4.2. Succeeded.

**Comment by mattrubin** [comment]
PR https://github.com/SwiftGit2/SwiftGit2/pull/145 migrated the project to Swift 4.2, and PR https://github.com/SwiftGit2/SwiftGit2/pull/146 migrated the project to Swift 5.

**Comment by lucascorrea** [comment]
Thanks dude.
