### ISSUE TITLE
Fixtures are set up only when you run all tests

### ISSUE THREAD

**Issue by DivineDominion** [SwiftGit2/SwiftGit2#135]
When you run 1 suite of tests only, say `RepositorySpec`, the Fixtures won't be set up at all, resulting in runtime exceptions. This means that you can only ever run all specs at once.

Unless this is intentional, I'd propose making the call to `Fixtures.shared.setUp` the first time when the shared instance is lazily created. If you folks agree, I'll follow through with a PR.

**Comment by mdiep** [comment]
The key thing is to only run that setup once. But I'd love to do that in a way that works to run only one suite.

**Comment by mdiep** [comment]
We can probably do this with the `XCTest` method instead.

**Comment by DivineDominion** [comment]
Wouldn't it suffice to make `Fixtures` a singleton the is set up only once, then create a `XCTestCase` subclass that calls this in `setUp`?

**Comment by mdiep** [comment]
Sure, that'd be fine. I think there's an XCTest method that would help here, but I can't remember the name.
