### ISSUE TITLE
Updating to Swift 4.2

### ISSUE THREAD

**Issue by arguiot** [SwiftGit2/SwiftGit2#143]
As Xcode 10.2 has been released, switching to Swift 4 is needed as it doesn't support Swift 3 anymore

**Comment by mdiep** [comment]
I think the work is mostly done in #137 if you want to finish it.

**Comment by mattrubin** [comment]
PR https://github.com/SwiftGit2/SwiftGit2/pull/145 migrated the project to Swift 4.2, and PR https://github.com/SwiftGit2/SwiftGit2/pull/146 migrated the project to Swift 5.
