### ISSUE TITLE
"could not open '/my/path/.git/config': Operation not permitted

### ISSUE THREAD

**Issue by mavris** [SwiftGit2/SwiftGit2#161]
This is my code:
`guard let url = URL(string:"/Users/myusername/Documents/Xcode/blah/my-project/") else {return}
        let repo = Repository.at(url)
        
        if case .success(let repository) = repo {
                debugPrint("Success")
        }
        else if case .failure(let error) = repo {
            debugPrint(error)
            
        }`

I get this error: 
**Error Domain=org.libgit2.libgit2 Code=-1 "could not open '/.git/config': Operation not permitted" UserInfo={NSLocalizedFailureReason=git_repository_open failed., NSLocalizedDescription=could not open '/.git/config': Operation not permitted}**

Any ideas?

**Comment by mavris** [comment]
The issue is that I hardcoded the URL. As soon as I use NSOpenPanel to find the file everything was fine

**Comment by UberJason** [comment]
For future reference for anyone else, I ran into the same issue and did not want to use an NSOpenPanel. I had to disable app sandbox in my Mac app's entitlements. It was on by default when I created the project.
