### ISSUE TITLE
Can't build to mac catalyst version

### ISSUE THREAD

**Issue by SpectralDragon** [SwiftGit2/SwiftGit2#171]
I got a next error message. I'm using manual installation to my project.

`in External/libgit2-ios/libgit2-ios.a(http_parser.c.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file 'External/libgit2-ios/libgit2-ios.a' for architecture x86_64`

**Comment by crutchcorn** [comment]
I'm facing the same issues, even when using `carthage update`. Admittedly, I had to use:

```
github "belkadan/SwiftGit2" "pointer-to-pointer"
```

To get the fixes from #176 to even hit this error myself

**Comment by crutchcorn** [comment]
This seems to be related to a change with XCode 12 and Apple silicon introduction, based on the convo here: https://github.com/flurry/flurry-ios-sdk/issues/207

**Comment by stevengharris** [comment]
I [forked SwiftGit2](https://github.com/stevengharris/SwiftGit2) and made a catalyst branch to produce separate iOS and Mac Catalyst frameworks. The README on the branch has some explanation. I also had to update to the latest OpenSSL, libssh2, and libgit2 while I was at it.

**Comment by kareman** [comment]
Nice. If you want to combine the frameworks I have a script for creating a .xcframework file in my spm-branch: https://github.com/kareman/SwiftGit2/blob/spm-binary-target/script/update_Clibgit2_xcframework

**Comment by BilalReffas** [comment]
This was merged already @crutchcorn :) Can we delete it ? @SpectralDragon

**Comment by SpectralDragon** [comment]
Yeah, I think we can close this issue)
