### ISSUE TITLE
Swift 5.3 support

### ISSUE THREAD

**Issue by arguiot** [SwiftGit2/SwiftGit2#175]
SwiftGit2 can't compile using the Swift 5.3 compiler. I'm using the `master` branch of this repository and I'm getting the following build error (formatted by XCPretty to be human-readable):
```
❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:592:36: cannot convert value of type 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>' to expected argument type 'UnsafeMutablePointer<Int8>'

                var paths = withExtendedLifetime(&dirPointer) {
           ^



❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:593:26: cannot convert value of type 'UnsafeMutablePointer<Int8>' to expected argument type 'Optional<UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>>'

                        git_strarray(strings: $0, count: 1)
                                                 ^



❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:592:36: cannot convert value of type 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>' to expected argument type 'UnsafeMutablePointer<Int8>'

                var paths = withExtendedLifetime(&dirPointer) {
                                              ^



❌  /Users/arguiot/GitHub/StudIO/Carthage/Checkouts/SwiftGit2/SwiftGit2/Repository.swift:593:26: cannot convert value of type 'UnsafeMutablePointer<Int8>' to expected argument type 'Optional<UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>>'

                        git_strarray(strings: $0, count: 1)
                                                 ^
```

According to my experience with this kind of error, it really shouldn't be hard to fix. It's just weird that the compiler is asking for a double `UnsafeMutablePointer` 🤷‍♂️

**Comment by kareman** [comment]
Check out #172 , it includes Swift 5.3 support.

**Comment by arguiot** [comment]
When do you expect #172 to be merged? Xcode 12 is already out and a lot of developers are trying to update their apps (including me).

If there is anything I can do to make the transition faster, let me know.

**Comment by kareman** [comment]
@arguiot  #172 is stuck because of what I assume is a bug in Xcode 12 beta, but I have extracted the swift 5.3 specific changes into the separate branch https://github.com/kareman/SwiftGit2/tree/Swift5.3 . I have verified locally that it builds the main target on both iOS and macOS in both Xcode 11.6 and Xcode 12 beta 2. It can't be merged into the main repository yet because the test dependency "Nimble" does not compile on macOS in Xcode 12. I will submit a PR to Nimble today.

But my branch can stil be used from other projects as they do not use the test dependencies.

**Comment by kareman** [comment]
And #172 will in any case not be merged into master until Xcode 12 and Swift 5.3 is out of beta: https://github.com/SwiftGit2/SwiftGit2/pull/172#issuecomment-641142384

**Comment by belkadan** [comment]
The fix in #172 is incorrect (actually, the current code is incorrect). I'll open a PR with the correct version. (I've been compiling the main library in 5.3 with this change and no other changes.)

**Comment by atom2ueki** [comment]
@belkadan wondering any plan to merge kareman's https://github.com/kareman/SwiftGit2/tree/spm-binary-target, since swift5.3 officially released

**Comment by kareman** [comment]
The code signing and archiving issues mentioned in https://github.com/SwiftGit2/SwiftGit2/pull/172 will have to be resolved first.
