### ISSUE TITLE
libgit versioning

### ISSUE THREAD

**Issue by twa16** [SwiftGit2/SwiftGit2#180]
Hello,
Is there a reason that this is still pinned to a pre-1.0 version of libgit? If not, is there any opposition to updating it? I think I may be hitting some little bugs with the underlying library while trying to add push support.

Thanks!

**Comment by mdiep** [comment]
This project hasn't been very actively developed. I think someone just needs to do the work. I'm not able to contribute right now, but I'm happy to add people as contributors.

**Comment by twa16** [comment]
I am glad to start taking a stab at adding blocks of functionality. I'd rather maintain the core version that split off entirely.
