### ISSUE TITLE
Cannot build carthage

### ISSUE THREAD

**Issue by light-tech** [SwiftGit2/SwiftGit2#190]
I tried building the framework with carthage on personal machine as well as [Azure Devops](https://lightech.visualstudio.com/SwiftGit2/_build/results?buildId=3639&view=logs&j=d7756252-827f-58ff-3922-552f77b43315&t=2cec588c-a387-5a7d-d767-54233808e31d&l=22)

Build locally using Xcode, the issue is during linking: there is no **pcre_free** function!

Have anyone fixed this?

**Comment by avnerbarr** [comment]
I can't build either

getting errors:

```
Repository.swift:593:37: error: inout expression creates a temporary pointer, but argument 'strings' should be a pointer that outlives the call to 'init(strings:count:)'
                var paths = git_strarray(strings: &dirPointer, count: 1)
                                                  ^~~~~~~~~~~
Repository.swift:593:37: note: implicit argument conversion from 'UnsafeMutablePointer<Int8>?' to 'UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>?' produces a pointer valid only for the duration of the call to 'init(strings:count:)'
                var paths = git_strarray(strings: &dirPointer, count: 1)
                                                  ^~~~~~~~~~~
Repository.swift:593:37: note: use 'withUnsafeMutablePointer' in order to explicitly convert argument to pointer valid for a defined scope
                var paths = git_strarray(strings: &dirPointer, count: 1)
                                                  ^
Diffs.swift:97:21: error: static property 'binary' produces an empty option set
                public static let binary     = Flags(rawValue: 0)
                                  ^
Diffs.swift:97:21: note: use [] to silence this warning
                public static let binary     = Flags(rawValue: 0)
                                  ^                 ~~~~~~~~~~~~~
                                                    ([])
```

**Comment by twa16** [comment]
What branch did you all try to build off of? Master?

**Comment by light-tech** [comment]
@avnerbarr @twa16 Try a bunch of approaches: kareman's fork and earlier commits.

Eventually got it to [build successfully](httphs://lightech.visualstudio.com/SwiftGit2/_build?definitionId=83) on Azure DevOps at commit 84e7f996aea9502e6dc29531ce658d4d1501dcf8.

I am trying out a [simple app](httphs://lightech.visualstudio.com/SwiftGit2) and run into **required module `Clibgit2` not found** upon `import SwiftGit2`!

**Comment by light-tech** [comment]
@avnerbarr @twa16 I used @kareman 's script to [make Clibgit2 XCFramework](https://lightech.visualstudio.com/SwiftGit2/_build/results?buildId=3682&view=results). Can run the test app now.
