### ISSUE TITLE
Documentation for implementation in Swift Projct

### ISSUE THREAD

**Issue by IpyCreator** [SwiftGit2/SwiftGit2#196]
Hi, I want to use this library as a git client iOS App, But there is no documentation for that. Is there any documentation for using this in my app.

**Comment by alexandermcpherson** [comment]
Yeah its very poorly documented

**Comment by joehinkle11** [comment]
You can use this repo as a reference. You could also include it in your iOS app to get a decent UI for an iOS gif client. Feel free to make a pull request if you have any enhancements 

https://github.com/App-Maker-Software/GitProviders

**Comment by DivineDominion** [comment]
Closing for now. Fixes and suggestions are welcome, but nobody has picked this up so far.
