### ISSUE TITLE
Build SwiftGit2 on Apple Silicon

### ISSUE THREAD

**Issue by hannesa2** [SwiftGit2/SwiftGit2#197]
How to make it work on a x86 and an arm64 mac ?
With an Homebrew arm64 the file is located at `/opt/homebrew/lib/libssh2.a`

![image](https://user-images.githubusercontent.com/3314607/153345133-738e4f1f-2370-4178-95f1-74fd5ffc6d06.png)

**Comment by hannesa2** [comment]
Because you have no arm64 runner, I used my custom arm64 runner https://github.com/hannesa2/SwiftGit2/pull/2 to have a smoke run.

But I run into 
<img width="1086" alt="image" src="https://github.com/SwiftGit2/SwiftGit2/assets/3314607/a2acd580-af49-4431-828b-9dcb8c158a99">

**Comment by DivineDominion** [comment]
@hannesa2 Could you check out `xcode-15` locally and maybe tweak your runners? I'm too inexperienced and slow with that, so I don't feel confident in getting that right. But it builds for my apps locally when I use that branch, and the binary also runs on all platform's I've tested.

**Comment by hannesa2** [comment]
Official Github runner only have Xcode 14 , please see https://github.com/hannesa2/SwiftGit2/actions/runs/6688925628/job/18171685874

Run ls -la /Applications/Xcode*
lrwxr-xr-x  1 runner  admin  28 Oct 17 23:06 /Applications/Xcode.app -> /Applications/Xcode_14.2.app
lrwxr-xr-x  1 runner  admin  28 Oct 17 23:00 /Applications/Xcode_13.1.0.app -> /Applications/Xcode_13.1.app
lrwxr-xr-x  1 runner  admin  30 Oct 17 23:00 /Applications/Xcode_13.2.app -> /Applications/Xcode_13.2.1.app
lrwxr-xr-x  1 runner  admin  30 Oct 17 23:00 /Applications/Xcode_13.3.app -> /Applications/Xcode_13.3.1.app
lrwxr-xr-x  1 runner  admin  30 Oct 17 23:00 /Applications/Xcode_13.4.app -> /Applications/Xcode_13.4.1.app
lrwxr-xr-x  1 runner  admin  30 Oct 17 23:00 /Applications/Xcode_14.0.app -> /Applications/Xcode_14.0.1.app
lrwxr-xr-x  1 runner  admin  28 Oct 17 23:00 /Applications/Xcode_14.1.0.app -> /Applications/Xcode_14.1.app
lrwxr-xr-x  1 runner  admin  28 Oct 17 23:00 /Applications/Xcode_14.2.0.app -> /Applications/Xcode_14.2.app

I wait till this is changes

**Comment by hannesa2** [comment]
I updated my custom runner to XCode 15 and there is still this issue https://github.com/hannesa2/SwiftGit2/actions/runs/6688925628/job/18813214445

**Comment by hannesa2** [comment]
When I change `MACOSX_DEPLOYMENT_TARGET = 10.13` https://github.com/hannesa2/SwiftGit2/pull/2/commits/a97041d9c7ee30f57bb7e08fa63c9c1b5dfbe706 it run into

```
ld: library 'crypto' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hannesa2** [comment]
Solved with https://github.com/SwiftGit2/SwiftGit2/pull/212
