### ISSUE TITLE
API to clone a repository

### ISSUE THREAD

**Issue by mdiep** [SwiftGit2/SwiftGit2#24]

**Comment by tombooth** [comment]
Do you have any opinions on how you would like this to look? I am looking at it now.

**Comment by mdiep** [comment]
I haven't looked at the libgit2 APIs in much detail, but this should:

1. Be a free function (not a method)
2. Return a `Result`
3. Only require a source URL and destination URL
4. Have optional parameters for everything else

Thanks!

**Comment by tombooth** [comment]
Great, that was the path I was following. I'll knocking something together and get it into a state for comment.

**Comment by mdiep** [comment]
:sparkles:

**Comment by tombooth** [comment]
I have a branch you can see at https://github.com/tombooth/SwiftGit2/pull/5 that should give you an idea of what I have done with cloning. I'd be curious of your opinion of it before I raise a pull request.

I am currently trying to work out why the tests are failing on iOS with what looks like a failed DNS lookup for github.com (https://travis-ci.org/tombooth/SwiftGit2/builds/113410338#L1815). If you've seen anything like it before pointers would be great.

**Comment by mdiep** [comment]
> I have a branch you can see at tombooth#5 that should give you an idea of what I have done with cloning. I'd be curious of your opinion of it before I raise a pull request.

I do have some feedback, but TBH I'd rather give it on a pull request against this repo! That keeps the history in a central place.

> I am currently trying to work out why the tests are failing on iOS with what looks like a failed DNS lookup for github.com (https://travis-ci.org/tombooth/SwiftGit2/builds/113410338#L1815). This is only on TravisCI, it works locally. If you've seen anything like it before pointers would be great.

Unfortunately, I have no idea. Sorry!

**Comment by tombooth** [comment]
Ok, I'll tidy up what I've got so far and raise a PR.
