### ISSUE TITLE
API to fetch a remote

### ISSUE THREAD

**Issue by mdiep** [SwiftGit2/SwiftGit2#32]

**Comment by mssun** [comment]
Any plan on these APIs?

**Comment by mdiep** [comment]
No plan, but PRs are welcome!

**Comment by mssun** [comment]
Thanks. I am new to Swift, wish I can contribute later.

**Comment by tengyifei** [comment]
Now that `fetch()` [is in](https://github.com/SwiftGit2/SwiftGit2/blob/97ee009ac5d48687fa35b6170334edfcbfb8ed0e/SwiftGit2/Repository.swift#L394), perhaps we can close this issue now?
