### ISSUE TITLE
Building with Carthage pulls in Result with breaking changes

### ISSUE THREAD

**Issue by mcb** [SwiftGit2/SwiftGit2#46]
Tried to install SwiftGit2 with carthage, however the build fails with the following:

```
*** Fetching SwiftGit2
*** Fetching Result
*** Checking out Result at "0.5"
*** Checking out SwiftGit2 at "v0.2"
*** xcodebuild output can be found in /var/folders/57/7jlwl0_11xn4w7wspwk3ntwr0000gn/T/carthage-xcodebuild.7HFaDu.log
*** Building scheme "Result-iOS" in Result.xcodeproj
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal x86_64 /[...]/Carthage/Checkouts/Result/Result/Result.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/[...]/Carthage/Checkouts/Result/Result/Result.swift:51:41: warning: 'ifSuccess ifSuccess' can be expressed more succinctly as '#ifSuccess'
/[...]/Carthage/Checkouts/Result/Result/Result.swift:4:31: error: use of undeclared type 'CustomStringConvertible'
/[...]/Carthage/Checkouts/Result/Result/Result.swift:4:56: error: use of undeclared type 'CustomDebugStringConvertible'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal x86_64 /[...]/Carthage/Checkouts/Result/Result/Result.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

carthage update  11.60s user 8.21s system 46% cpu 42.756 total
```

As `CustomStringConvertible` is not available Swift that ships with Xcode 6.3.x, and Result 0.5 adds changes for Swift 2, one needs to either change Result to a lower version or use the Xcode Beta.

I tried to change the Cartfile to 
`github "antitypical/Result" == 0.4.1`

but this seemed to not do the trick. I am not sure what causes this, as of now I am building it manually and just wanted to let you know.

**Comment by mdiep** [comment]
It sounds like you ran `carthage update` instead of `carthage bootstrap`.

**Comment by mcb** [comment]
Actually I ran ```carthage bootstrap```.

Removing Carthfile.locked and Carthage-Folder again and rerunning ```carthage bootstrap``` results in the same as before, just wanted to make sure I remembered well.

Nevertheless it might make sense fixing the version, as Result 0.5 introduces breaking changes, wouldn't it?

Thanks for your time, @mdiep

**Comment by mdiep** [comment]
We'll definitely want to upgrade, but SwiftGit2 should build as is. I think you're on a really old version of Carthage and need to upgrade.

**Comment by mcb** [comment]
It's as old as 7 days:

```
~% carthage version
0.7.4
```

**Comment by mattrubin** [comment]
This issue is quite old, and all of the pieces in play here (Xcode, Swift, Carthage, and SwiftGit2) have been updated since it was opened, so I'm going to close the issue.
