### ISSUE TITLE
error when building the lib for os x

### ISSUE THREAD

**Issue by Tobisaninfo** [SwiftGit2/SwiftGit2#62]
I tried to build the lib for os x but get the error 127 return code from the build file.
For adding the lib to the xcode project, I followed the steps you wrote.

**Comment by mdiep** [comment]
This project hasn't gotten much attention and hasn't been updated for recent versions of Xcode. PRs welcome!

**Comment by mattrubin** [comment]
The project has been updated for the latest versions of Xcode and appears to build just fine, so I'm going to close this issue.

@Tobisaninfo: If you're still having this problem and can provide more details about reproducing it, feel free to reopen the issue.
