### ISSUE TITLE
[Code Style] Trailing whitespace on blank lines

### ISSUE THREAD

**Issue by mattrubin** [SwiftGit2/SwiftGit2#73]
While [configuring SwiftLint](https://github.com/SwiftGit2/SwiftGit2/pull/71), I noticed the use of trailing whitespace on blank lines is inconsistent. Some blank lines are indented to match the surrounding code, while other empty lines have no whitespace, even in the midst of indented chunks of code. By my count, across the SwiftGit2 library source and tests there are 313 indented blank lines (`^\h+$`) and 76 completely empty lines among indented code (`^\v\h`).

Debates about whitespace often boil down to subjective personal preference – and major reformatting of code for its own sake isn't the best use of time – but I think regardless of the outcome it would be nice to update the code for _consistency_ in whitespace usage.

The [GitHub Swift style guide](https://github.com/github/swift-style-guide#whitespace) linked from the README argues against blank line whitespace ("Don’t leave trailing whitespace... Not even leading indentation on blank lines."), and my personal preference is also to leave blank lines empty. Any strong opinions for or against trailing whitespace on blank lines?

**Comment by Uncommon** [comment]
Personally I think it makes the most sense for blank lines to match the surrounding indentation level. For one thing, it makes it easier to add something at that blank link since you don't have to re-indent.

**Comment by mdiep** [comment]
I'm ambivalent. But I'd happy to have style enforcement either way.

**Comment by mattrubin** [comment]
I've opened a PR to remove trailing whitespace on blank lines.
 - This style conforms to the project's [Swift style guide](https://github.com/github/swift-style-guide).
 - SwiftLint has a rule to enforce this style.
 - Xcode has a preference to auto-apply this style.
