### ISSUE TITLE
Enable PR linting with Hound

### ISSUE THREAD

**Issue by mattrubin** [SwiftGit2/SwiftGit2#76]
Hound can be configured to run SwiftLint for the code changed in each PR: http://help.houndci.com/configuration/swiftlint

**Comment by mattrubin** [comment]
1. Go to [Hound's GitHub Marketplace page](https://github.com/marketplace/hound/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xMDYx#pricing-and-setup).
2. Make sure the free Open Source plan is selected.
3. To the right, select SwiftGit2 from the "Account" dropdown.
4. Click "Install it for free".
5. Confirm the correct plan and account have been selected, then click "Complete order and begin installation".
6. Select which repositories Hound should have access to, then click "Install".
7. In the Hound UI, click the "Activate" button for the SwiftGit2 repo.

**Comment by mdiep** [comment]
Done!

**Comment by mattrubin** [comment]
Hound is now linting new PRs! 🎉
