### ISSUE TITLE
README instructions for importing SwiftGit2 not working

### ISSUE THREAD

**Issue by profburke** [SwiftGit2/SwiftGit2#81]
I have included the dependency on SwiftGit2 in my project's Cartfile. When I run carthage update, it downloads and builds Result fine, but it downloads a pre-built OSX binary that is out of date. Below is the output from the update command (note, not the actual log, just the messages printed to the terminal):

*** Fetching SwiftGit2
*** Fetching Result
*** Checking out Result at "3.1.0"
*** Downloading SwiftGit2.framework binary at "0.2: Top Banana"
*** xcodebuild output can be found in /var/folders/lk/rph7cj_n4q34zkb7974y5tlrfb2t0x/T/carthage-xcodebuild.tGDu0J.log
*** Building scheme "Result-Mac" in Result.xcodeproj
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "Result-watchOS" in Result.xcodeproj
*** Building scheme "Result-tvOS" in Result.xcodeproj

I clearly need to do some more reading on Carthage, but it seems like something is mis-configured with SwiftGit2 since it's grabbing the wrong file.

**Comment by mattrubin** [comment]
Carthage is using [the last tagged release](https://github.com/SwiftGit2/SwiftGit2/releases/tag/v0.2) of SwiftGit2, which is several months out of date.

You can check out the source and ignore the pre-built binary by passing the `--no-use-binaries` option to Carthage

To use the very latest SwiftGit2, you can track the master branch in your Cartfile:
```
github "SwiftGit2/SwiftGit2" "master"
```
Note that because of the large dependencies, Carthage's build of SwiftGit2 will take a long time to complete.

**Comment by profburke** [comment]
Thanks. I know Carthage how-to is a little off topic, so I appreciate the help!

**Comment by mattrubin** [comment]
@mdiep I think so. Looking at it again, the last release was April of 2015. It looks like some functionality was added [between then and April 2016](https://github.com/SwiftGit2/SwiftGit2/compare/v0.2...f097301ed731011c5105b8e41f0a1e861a667366), plus [all the recent build and compatibility updates for Swift 3](https://github.com/SwiftGit2/SwiftGit2/compare/f097301ed731011c5105b8e41f0a1e861a667366...master). I wouldn't say this is 1.0, but I think it certainly merits an 0.3.

**Comment by mdiep** [comment]
https://github.com/SwiftGit2/SwiftGit2/releases/tag/v0.3
