### ISSUE TITLE
Perform git status in SwiftGit2

### ISSUE THREAD

**Issue by gonzolino** [SwiftGit2/SwiftGit2#97]
Is it possible to do an equivalent of `git status` in SwiftGit2?
If not, how complicated would it be to implement that?

**Comment by mdiep** [comment]
That's not currently implemented.

I don't know how to quantify how much effort it would take. You can probably work from the existing code and add something without too much work. But I can't say for sure.

**Comment by mdiep** [comment]
The is being worked on in #102.

**Comment by ansonj** [comment]
Looks like #102 was merged in February. Should this issue be closed now?
